# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.9'

services:
  peer0.betweenorganization.example.com:
    container_name: peer0.betweenorganization.example.com
    image: hyperledger/fabric-peer:${IMAGE_TAG:-latest}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  peer0.bank1organization.example.com:
    container_name: peer0.bank1organization.example.com
    image: hyperledger/fabric-peer:${IMAGE_TAG:-latest}
    profiles:
      - bank1
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  peer0.bank2.example.com:
    container_name: peer0.bank2.example.com
    image: hyperledger/fabric-peer:${IMAGE_TAG:-latest}
    profiles:
      - bank2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  peer0.bankd.example.com:
    container_name: peer0.bankd.example.com
    image: hyperledger/fabric-peer:${IMAGE_TAG:-latest}
    profiles:
      - bankd
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:${IMAGE_TAG:-latest}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ${DOCKER_SOCK}:/host/var/run/docker.sock
